CREATE TABLE `users` (
-- Your code here
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `channels` (
-- Your code here
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `chats` (
-- Your code here
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `blocks` (
-- Your code here
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `follows` (
-- Your code here
) ENGINE=InnoDB DEFAULT CHARSET=utf8;